ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM amazeeio/nginx-drupal

COPY nginx-app.conf /etc/nginx/conf.d/app.conf
COPY nginx-fastcgi.conf /etc/nginx/fastcgi.conf
COPY nginx-redirects.conf /etc/nginx/redirects-map.conf

COPY --from=cli /app /app

# Define where the Drupal Root is located
ENV WEBROOT=web
