version: '2.3'

x-lagoon-project:
  &lagoon-project allianz

services:
  tests:
    image: *lagoon-project
    working_dir: /app/web
    command: "sh -c 'sleep 5 ; ./test.sh'"
    environment:
      LAGOON_PROJECT: *lagoon-project
      LAGOON_ROUTE: http://allianz.docker.amazee.io
    volumes_from:
      - cli
    networks:
      - default
      - web
    depends_on:
      - nginx
      - php
      - mariadb
      - redis

