<?php

/**
 * @file
 * Helper module for the Password Enhancements tests.
 */

declare(strict_types = 1);

/**
 * Copyright (C) 2020 PRONOVIX GROUP BVBA.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function password_enhancements_display_constraints_test_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  $form_ids = ['user_form', 'user_register_form'];
  if (in_array($form_id, $form_ids) && isset($form['account']['pass'])) {
    $form['account']['pass']['#access'] = \Drupal::state()->get('password_enhancements_test.display_password_field') ?? TRUE;
    // User register form is cached for anonymous user and it is the only way
    // to make it uncachable at this moment.
    \Drupal::service('page_cache_kill_switch')->trigger();
  }
}
