<?php

/**
 * @file
 * Test module for testing the Devportal API Docs module.
 */

declare(strict_types = 1);

/**
 * Copyright (C) 2020 PRONOVIX GROUP BVBA.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 */

/**
 * Implements hook_install().
 */
function dp_api_docs_test_install(): void {
  $config_factory = \Drupal::configFactory();
  $form_display = $config_factory->getEditable('core.entity_form_display.node.api_basic_page.default');
  $form_display_dependencies = $form_display->get('dependencies');
  $form_display_dependencies['config'][] = 'field.field.node.api_basic_page.field_visibility';
  $form_display->set('dependencies', $form_display_dependencies);
  $form_content = $form_display->get('content');
  $form_field_visibility_field = [
    'weight' => 26,
    'settings' => [
      'match_operator' => 'CONTAINS',
      'match_limit' => 10,
      'size' => 60,
      'placeholder' => '',
    ],
    'third_party_settings' => [],
    'type' => 'entity_reference_autocomplete',
    'region' => 'content',
  ];
  $form_content['field_visibility'] = $form_field_visibility_field;
  $form_display->set('content', $form_content);
  $form_display->save();

  $view_display = $config_factory->getEditable('core.entity_view_display.node.api_basic_page.default');
  $view_display_dependencies = $view_display->get('dependencies');
  $view_display_dependencies['config'][] = 'field.field.node.api_basic_page.field_visibility';
  $view_display->set('dependencies', $view_display_dependencies);
  $view_display_hidden = $view_display->get('hidden');
  $view_display_hidden['field_visibility'] = TRUE;
  $view_display->set('hidden', $view_display_hidden);
  $view_display->save();
}
