password_enhancements.constraint_plugin.special_character:
  type: mapping
  label: 'Configuration: Special character'
  mapping:
    required:
      type: boolean
      label: 'Required'
    minimum_characters:
      type: integer
      label: 'Minimum characters'
    descriptionSingular:
      type: label
      label: 'Description (singular)'
    descriptionPlural:
      type: label
      label: 'Description (plural)'
    use_custom_special_characters:
      type: boolean
      label: 'Define special characters'
    special_characters:
      type: string
      label: 'Special characters'
