password_enhancements.constraint_plugin.number:
  type: mapping
  label: 'Configuration: Number'
  mapping:
    required:
      type: boolean
      label: 'Required'
    minimum_characters:
      type: integer
      label: 'Minimum characters'
    descriptionSingular:
      type: label
      label: 'Description (singular)'
    descriptionPlural:
      type: label
      label: 'Description (plural)'
