password_enhancements.settings:
  type: config_object
  label: 'Settings'
  mapping:
    constraint_update_effect:
      type: string
      label: 'Constraint update effect'
    require_password:
      type: boolean
      label: 'Require password'
    require_password_change:
      type: boolean
      label: 'Require password change'
