user.role.*.third_party.password_enhancements:
  type: mapping
  label: 'Password enhancements policy'
  mapping:
    expireSeconds:
      type: integer
      label: 'Expire seconds'
    expireWarnSeconds:
      type: integer
      label: 'Expire warn seconds'
    expiryWarningMessage:
      type: text
      label: 'Expiry warning message'
    minimumRequiredConstraints:
      type: integer
      label: 'Minimum required constraints'
    constraints:
      type: sequence
      label: 'Constraints'
      sequence:
        type: password_enhancements.constraint

password_enhancements.constraint:
  type: mapping
  label: 'Constraint'
  mapping:
    uuid:
      type: uuid
      label: 'UUID'
    id:
      type: string
      label: 'Plugin ID'
    data:
      type: password_enhancements.constraint_plugin.[%parent.id]
